### ISSUE TITLE
Adjustable Inventory Size support

### ISSUE THREAD

**Issue by re-coilless** [DrChaleceCume/index_core#4]
https://steamcommunity.com/sharedfiles/filedetails/?id=2336685059&searchtext=Adjustable+Inventory+Size

**Comment by XM666-Dev** [comment]
I tried Adjustable Inventory Size again.
There's only one row of inventory, but when I open a chest, three rows of inventory are come back. And the wand spell editor has also disappeared.
Reentering the game can't solve this problem.
![shot_20240124-103937-767225887--653-1407-00089484](https://github.com/DrChaleceCume/index_core/assets/99076011/f7646408-117a-4d15-a2d5-89418b737708)
![shot_20240124-103941-767225887--653-1410-00089683](https://github.com/DrChaleceCume/index_core/assets/99076011/795ccfb9-37a2-4770-b114-e3b9ca7a4da9)

**Comment by re-coilless** [comment]
OH, I see
Right, that's what having no proper tutorial, as for now, does to UX (and it seems something broke?).

The inventory has global modes (you can usually see the thing that switches them above the spell inventory) and stuff like extended full inventory or wand editing capabilities are controlled by them to escape conflicts like wands obstructing spell storage for example. For some reason however, it appears that for you this UI element is not present at all, hm.
![image](https://github.com/DrChaleceCume/index_core/assets/68288735/70cb350b-7d20-4002-9feb-293612d27339)
![image](https://github.com/DrChaleceCume/index_core/assets/68288735/1552d39e-25ff-4be5-aac0-b59a481cc72b)

**Comment by re-coilless** [comment]
As for the fixes, I can make a setting, so the spell inventory would behave just like it does in vanilla + I'd highly suggest running this mod in dev.exe (it's in the same folder as the main executable), since it will show you all the lua errors for effective debugging.
