### ISSUE TITLE
Disable this mod will break the game.

### ISSUE THREAD

**Issue by XM666-Dev** [DrChaleceCume/index_core#6]
![shot_20240124-105520-767225887-212-1337-00101959](https://github.com/DrChaleceCume/index_core/assets/99076011/e5c08f42-0fd3-4176-9ead-8bd6efbf3586)
![shot_20240124-105817-767225887--36-1466-00102101](https://github.com/DrChaleceCume/index_core/assets/99076011/052b3333-6472-4ff9-8068-0354ee31b485)
![shot_20240124-110128-767225887--161-1360-00113350](https://github.com/DrChaleceCume/index_core/assets/99076011/ef18918f-6466-4626-989f-f1577d69fef8)
Everything can't come back... It breaks my game.
I have disabled these mods, but the GUIs has break.
Can't even edit my wand.

**Comment by re-coilless** [comment]
Yeah, that's just how the game is really - you can't normally remove huge mods like this without obliterating the savefile, only starting new game will work properly. The most I can do is add a special check to the main inventory controller, so I will self-destruct if the mod is disabled, but this won't work at all for the steam version once it releases.
